### ISSUE TITLE
Gazebo must be run before Koord apps

### ISSUE THREAD

**Issue by jzw2** [cyphyhouse/CyPhyHouseExperiments#1]
main.py needs to know the position of the drone before being run. Running Gazebo will give it the position.

**Comment by hc825b** [comment]
Right now this is temporarily handled with a sleep between starting Gazebo and starting agents in `cph/__main__.py`
When more agents are required, the delay should be longer, so sleeping for a fixed duration is not working well.

**Comment by hc825b** [comment]
Won't fix this issue.

As specified in README, user is instructed to first manually start Cymulator which in turn starts Gazebo to spawn all simulated vehicles. This is similar in deployment that you have to manually boot up all real vehicles before running Koord applications.
